#register(post)
http://localhost:7070/api/auth/register

{
    "username" : "hoanghac",
    "password" : "123456",
    "email" : "hoanghac@gmail.com",
    "address" : "District 9",
    "phone" : "09588564822"
}

#login(post)
http://localhost:7070/api/auth/login
{
    "username" : "hoanghac",
    "password" : "123456"
}